### ISSUE TITLE
Background color grey should go darker

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#150]
I think we need to stick with current DL spec. The gray 10 is too light to offer contrast against white. I think we used a grey 10 hover spec because grey 20 is too dark. @jeanservaas Sadek has spec too.

**Comment by alisonjoseph** [comment]
Is this a background color change for the Gatsby theme/all sites, or just the IDL site specifically?

**Comment by jeanservaas** [comment]
I get that we want to use the darker background (the e5e5e5) color to showcase our gray 10 usage images... but I still think being consistent with our ui-backgrounds and our light themes out-weighs that. I don't think adding a delicate stroke to our gray 10 usage images is a bad compromise and I'm not sure what you mean by gray 10 not offering enough contrast against the white... in what instance? Because the Gray 10 background with white contrainers is being used now throughout product.

I also think, if we make this background change for DL we need to make it for Gatsby and in turn, all of our docs sites for consistency... why would only DL get the slightly darker background — especially when Carbon has the same challenges. 

To the same point, I'm also assuming that DL will either take Carbon's tab components or Carbon will take DL's... all of these moments should eventually be streamlined.

**Comment by mjabbink** [comment]
Let’s stick to grey 10 and I reckon at one point we can add a light grey 30 stroke.

The low contrast comes from presenting the design eco sites to people on TVs or from  projectors
