### ISSUE TITLE
Landing page: mobile: Horizontal rule not centered in image

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#161]
Staging:

![IMG_3852](https://user-images.githubusercontent.com/32881239/62734736-b5d1d880-b9f7-11e9-993a-66a75b8aefee.JPG)

—————
Expected:

![IMG_3851](https://user-images.githubusercontent.com/32881239/62734769-c8e4a880-b9f7-11e9-947a-d626a6bbf8c5.JPG)

**Comment by emyarod** [comment]
@alisonjoseph are you able to replicate this issue? I can't on my end

**Comment by alisonjoseph** [comment]
I'm also unable to duplicate, checked chrome/safari on my iphone X.

**Comment by emyarod** [comment]
@mjabbink if this issue still appears on your end feel free to reopen the issue along with some more details on how we might be able to replicate it!

**Comment by mjabbink** [comment]
It is still happening here: https://design-language-website.netlify.com/

But I think this is old?

**Comment by mjabbink** [comment]
I still see it in mobile both chrome and safari. iPhone X

**Comment by emyarod** [comment]
could you try viewing in incognito mode to make sure the device isn't caching old files?

**Comment by alisonjoseph** [comment]
Oh wait, I was misunderstanding what the issue was. Yep I can see it. @emyarod see the difference between staging and live site. I believe he wants the buttons to stretch to fill the vertical space on mobile and not keep the aspect ratio? Or do you only want the video to be as tall as the two buttons at the correct aspect ratio?

Can you confirm @mjabbink ?

![IMG_1187](https://user-images.githubusercontent.com/2753488/63023522-eb007f80-be6a-11e9-9fa3-811adc299f43.PNG)
![IMG_1186](https://user-images.githubusercontent.com/2753488/63023523-eb007f80-be6a-11e9-88f5-fb4a3335736d.PNG)

**Comment by emyarod** [comment]
this issue still not quite clear to me, would you mind adding more details to help explain?

**Comment by alisonjoseph** [comment]
The "cards" that sit on top of the video should be 50% height each of the video at mobile view. Right now they are smaller.
