### ISSUE TITLE
Icon library: search should be sticky

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#183]
@jeanservaas I believe Chiu and/or Shix had specs or a design. Should sit in a container with 8 or 16px under the search field. Icons scroll underneath. Could have very subtle drop shadow maybe?

Safekeepings can send specs if you cannot find files

**Comment by mjabbink** [comment]
I think I have a animation of this chiu did moons ago and will send

**Comment by peter-garvin** [comment]
@mjabbink Working off the spec that @laurenmrice sent me. Is this what you had in mind? couple questions

1. Are we thinking the category label would exist until it sticks at the top? You had mentioned to take it out on the sticky spec

2. Everything is pretty straightforward until we get to mobile. How do we feel about this mobile pattern? 


<img width="859" alt="Screen Shot 2019-08-23 at 10 54 30 AM" src="https://user-images.githubusercontent.com/47458576/63605880-762cf400-c594-11e9-9715-e06a703407a1.png">
<img width="1620" alt="Screen Shot 2019-08-23 at 10 54 41 AM" src="https://user-images.githubusercontent.com/47458576/63605888-788f4e00-c594-11e9-9371-b6215e67f971.png">

**Comment by mjabbink** [comment]
this seems nice to me. Have Jeannie give it a look over as well. I think the mobile pattern works.

**Comment by laurenmrice** [comment]
@jeanservaas

**Comment by jeanservaas** [comment]
This looks good to me, @laurenmrice and I were just wondering how the search interaction works on mobile. Mike says search field expands over category if you tap on icon. That's the only interaction where I see @vpicone having questions.

**Comment by mjabbink** [comment]
Why can’t it just stack like it already is but make it sticky and with drop shadow?

.


![File (54)](https://user-images.githubusercontent.com/32881239/63612006-29a0e300-c5ab-11e9-8cc6-a7406b9d0f69.jpg)

**Comment by mjabbink** [comment]
and let’s lose the dumb quotes in search!

**Comment by laurenmrice** [comment]
good catch ! second dumb quote find today!

**Comment by peter-garvin** [comment]
Another option for mobile

<img width="1151" alt="Screen Shot 2019-08-23 at 2 15 34 PM" src="https://user-images.githubusercontent.com/47458576/63617972-7d61fb00-c5b0-11e9-9ba1-89dfaf13f75e.png">

**Comment by mjabbink** [comment]
yes!

**Comment by shixiedesign** [comment]
Finally read through the whole thread! FYI @jeanservaas My thoughts: 

### +1 on multi-select filter icon dropdown. 

Saves real estate. However, @peter-garvin I think we need a few selected state. What happens when the dropdown is closed with a few options selected? Maybe there be a badge on the filter icon with a little number in it...? Users need to know what they see is a filtered result. 

### I will also vote +1 on gray 50 underline for accessibility. 

I'm sure Data table's search will come back to hunt us in no time. V10 Carbon didn't get to do a proper refresh of the Data table **toolbar** bit. Search there was supposed to be a button, which would have hover and button appearance. But then later someone asked for it to be pinned open because it's an essential function for them, and that's how we got here. That search bar is not Carbon's actual search component.

**Comment by mjabbink** [comment]
we may not need multi-state which would simplify things.

**Comment by mjabbink** [comment]
I’m not sure why the rule is needed to be accessible. There is an icon and a word (Search) and a focus state. Does that not make it accessible?

**Comment by shixiedesign** [comment]
The requirement is for non-elements (WCAG 1.14.11). https://www.w3.org/TR/WCAG21/#non-text-contrast:
![image](https://user-images.githubusercontent.com/15144993/64040050-b99dda00-cb21-11e9-95a4-efcae753a277.png)

Here are some examples they gave: 
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html
![image](https://user-images.githubusercontent.com/15144993/64040238-38931280-cb22-11e9-914a-940b613cdea7.png)

**Comment by shixiedesign** [comment]
Even non-multi-state we still need a selected state to indicate it's active and doing something to page. My thought:

![image](https://user-images.githubusercontent.com/15144993/64042072-b2c59600-cb26-11e9-9926-61ac73bc3259.png)

Regarding the underline, the rules are difficult to interpret. In Carbon components we went with keeping the underline to be safe, and to differentiate fields from buttons as a systematic treatment difference. Below are both sides of the argument to keep vs not keep the underline all according to WCAG. I loop in @aagonzales always for any accessibility fun 😂 

The requirement is for non-elements (WCAG 1.14.11). https://www.w3.org/TR/WCAG21/#non-text-contrast:
![image](https://user-images.githubusercontent.com/15144993/64040050-b99dda00-cb21-11e9-95a4-efcae753a277.png)

Here are some examples they gave: 
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html
![image](https://user-images.githubusercontent.com/15144993/64040238-38931280-cb22-11e9-914a-940b613cdea7.png)


Arguments for NOT keeping underline. Since the search icon is 4.5:1 accessible, it's considered passed. But this treatment doesn't differentiate our input field from buttons.

![image](https://user-images.githubusercontent.com/15144993/64042201-fd471280-cb26-11e9-8760-2494655b74ae.png)

**Comment by mjabbink** [comment]
I like the little dot with number to show number of selections

**Comment by mjabbink** [comment]
And the line needs to go back in

**Comment by mjabbink** [comment]
@jeanservaas we did this? Awesome!

**Comment by vpicone** [comment]
@laurenmrice @jeanservaas the dropdown/multiselect icon isn't something we have in Carbon right now. Wondering if you just want to stack a regular multi select underneath or make our own bespoke component for this behavior.

**Comment by vpicone** [comment]
More specifically: changing the icon of the dropdown and having an 'active' inverted state isn't a thing at the moment and would require component enhancment, the alternative is just having the menu wrap on mobile (as it does now) but making the whole thing sticky.

It takes up a significant chunk of the viewport with 4 items stuck to the top (shell, tabs, search, and category dropdown)

**Comment by mjabbink** [comment]
I believe @chrisconnors-ibm and I agree the libraries should reside in the Idl site. There are no tabs there. So it would be shell, search only. It’s not clear to me why we cannot have the search and the dropdown on the same level?

**Comment by vpicone** [comment]
The form input (Dropdown) doesn't support alternative icons so this would require some component enhancement to make it more flexible and support an icon-only dropdown. 

The OverflowMenu is a closer solution, but is meant for navigation and doesn't have any logic for active/selected items like a form input (Dropdown) does.

**Comment by chrisconnors-ibm** [comment]
@jeanservaas what's the requirement for multi-select categories? right now it's one category or no category (all) on the icon page.

**Comment by vpicone** [comment]
@chrisconnors-ibm the spec has options for both multi-select and regular. Unfortunately both options aren't feasible without creating a new component or heavily modifying the dropdown/multiselect components upstream.

The current implementation in #312 wraps the input underneath on mobile and makes it sticky. This is the pattern we use for the other sticky content filters:  https://www.ibm.com/design/language/elements/type-specs-ui/#type-set

**Comment by mjabbink** [comment]
ok, let’s go with the stacked search/dropdown for now. Space/realestate is a non issue since it’s a minimal use case and not a big deal for this content. I have zero issue with it as a user.

**Comment by chrisconnors-ibm** [comment]
> @chrisconnors-ibm the spec has options for both multi-select and regular. Unfortunately both options using the filter icon dropdown aren't feasible without creating a new component or heavily modifying the dropdown/multiselect components upstream.

Yes I'm asking _why_ the spec has multi select since I'm unclear what use cases it solves - setting aside the fact that it represents additional dev work/time on the component.

**Comment by rcwakelin** [comment]
@mattrosno adding you to chain
