### ISSUE TITLE
[IDL] Update Carbon Pictograms Contribution page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#528]
**Background/Problem:** The process for design/approving UI-Icons and Pictograms is changing. We need to request a change on the page

![Screen Shot 2020-02-14 at 4.06.08 PM.png](https://zenhub.ibm.com/images/59c27f0f71aa2e2d58882196/f85e6b76-54d9-47b2-8be1-8c556438a2ca)

**Copy**

- [ ] Producing an icon

•	Create a 32 x 32 px artboard for each pictogram.
•	32 px pictograms should have 1 px padding.
•	Set your workspace up from the start to snap to grid.
•	Be aware of automatic alignments which can place vectors on uneven or half pixels.
•	The pictogram should be on the top-most layer in your artboard. Strokes should be grouped appropriately.
•	Make sure to properly name layers and artboards (these names will also be exported into the code).

- [ ] Production-ready

•	To be considered production-ready, all pictogram submissions must be delivered in Adobe Illustrator format at 32 x 32 px with strokes kept intact.
•	Each artboard and the artwork within it must be aligned to the pixel grid wherever possible.
•	All strokes should be kept as is and not converted to shapes.
•	Group strokes logically whenever possible.

- [ ] Contribution process

Does your pictogram have potential for other materials at IBM? If so, please consider contributing to the design system. IBM welcomes pictogram contributions in the form of a pull request to our pictogram repository (coming soon). For now, to make a pull request, please submit an issue in the repo [bolded text should be a link to here: https://github.ibm.com/brand/pictograms/issues] with the pictogram attached.
Please note that Carbon contribution is **not required** in order to introduce a new pictogram into your materials. If your pictogram is determined to be broadly useful in Carbon and passes IBM Brand design reviews, then it may also be integrated into the design system.
If your submission is accepted, the team will notify you. If changes are needed, you’ll need to create a new contribution issue after reworking it based on feedback from the Design System and Brand teams.

@conradennis Is the above the final copy from Lori?

**Comment by vpicone** [comment]
@andreancardona not sure if you moved the svg library components yet, but if you could include this copy update in your PR for IDL and Carbon it'd probably prevent someone else's merge-conflict headache.

**Comment by andreancardona** [comment]
The issue for the `Carbon site: Update Carbon Pictograms Contribution page` can be found below: 

- Issue: https://github.com/carbon-design-system/carbon-website/issues/1187
- PR: https://github.com/carbon-design-system/carbon-website/pull/1188

**Comment by janchild** [comment]
Hi @mjabbink, we have a "How to contribute" section in the Carbon left nav. Shouldn't we put this content there? @connor-leech brought this up yesterday and I think it's a great point. The current tab solution for icons and pictograms may have been put in place because the Contribution section was messy but Connor and I did a revamp of the Contribution IA and content last year and these pages would slot in nicely there. 

Both icons and pictograms could have their own page as a second-level nav item. It would certainly raise the visibility. We can put cross-references to these pages from the usage pages.

**Comment by mjabbink** [comment]
That is a good point @janchild. IDL does have a left nav contribution but let me discuss this with @sadekbazaraa but agree for IDL a “Contribute”page inside “Iconography” is better than tabs

**Comment by sadekbazaraa** [comment]
@janchild @mjabbink I think the issue with the current IA on IDL is that we don't have third level navigation and we nest things under categories such as 'Typography' and 'Iconography' which is why we have Contribute as a tab vs. a menu item.

![Screen Shot 2020-05-13 at 11 36 57 AM](https://user-images.githubusercontent.com/33162280/81834084-8152f600-950e-11ea-8052-b882d276f557.png)

I suppose one solution would be to create an L1 page in the left nav called 'How to contribute' where we talk about contribution at a high level and then link off to the contribute tabs on their respective pages which currently includes: Pictograms and UI Icons and may eventually include Illustration as well.

**Comment by janchild** [comment]
Oh okay, @sadekbazaraa and @mjabbink. I was actually referring to the Carbon site because we already have a "How to contribute" section. We have the different types of contributions as a second level nav item. 
![Screen Shot 2020-05-13 at 11 36 40 AM](https://user-images.githubusercontent.com/44503588/81840254-55d00b80-950e-11ea-96aa-7350d6db557a.png)

I'm reviewing the PR for the pictogram contribution page on Carbon (https://github.com/carbon-design-system/carbon-website/pull/1188), and we could include this page in the "How to contribute" section at least on Carbon for now, but it would be an easy model for IDL to follow also.

**Comment by mjabbink** [comment]
@janchild @sadekbazaraa  Do not move this IDL page and stick to the original issue plan. We are not creating a L1 Contribution page right now. Can think this over for another day. Proceed as planned.

**Comment by mjabbink** [comment]
@conradennis and I should look over a staging link. Can you make one @andreancardona?

**Comment by janchild** [comment]
@mjabbink I misunderstood. I thought this was for the Carbon site. I was only suggesting we move this page on the Carbon site because we already have an L1 Contribution section there.

**Comment by mjabbink** [comment]
@janchild Gotcha. I think the content should get checked so that whatever you’re saying in the Carbon page is the same. We’re aiming people to the Repo for UI icons and Pictograms for them to contribute or make iconography requests or proposals. Currently Pictograms link to icon repo which is wrong. This issue it meant to resolve broken links and we also updated our content to be more clear.
