### ISSUE TITLE
Explore more emphasis to drive to Carbon as Digital Design system.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#718]
Things to explore

Maybe a horizontal card (like the scale of Carbon homepage ones) on the top with Card (Carbon Design System)
and Elements (as they are or edited down) underneath.

or

- [ ]  Update first Card to say **“Carbon Design System”** and Link to Carbon landing page instead of Carbon components.

- [ ]  Add an **“About”** in left nav and really layout IDLs purpose and aim to Carbon Design system, explain switcher and other design discipline sites. Similar to “Expressions page with smaller cards to each. An opportunity or snap shot for clear explanation to a Journey (emphasis on new comers to IBM)

- [ ]  **Also reconsider the Switcher content.** Confusion around it for many users. Most are unclear. Carbon team exploring as well for a solution. Switcher needs to be clear as well as better clarity and direction in sites.

i.e. maybe Headers/labels change to something like this? @janchild is playing around with ideas.

**Foundation**
        IBM Brand Center
        IBM Design
        IBM Design Language
        IBM Accessibility

**System & Disciplines**
        Carbon Design System
        Event Design
        Workplace Design

**Practices**
        Enterprise Design Thinking
        IBM Design Research
        IBM Design for AI
        IBM iX (edited) 

@sadek

**Comment by mjabbink** [comment]
latest thought

**Foundation**
IBM Brand Center
IBM Design
IBM Design Language
IBM Accessibility

**Disciplines**
Carbon Design System
Event Design
Workplace Design

**Practices**
Enterprise Design Thinking
IBM Design Research
IBM Design for AI
IBM iX (edited)

**Comment by sadekbazaraa** [comment]
@mjabbink there's a lot of good thoughts in here for sure. I think the content switcher updates can happen sooner than later and this list makes a lot of sense. I see the move to take away "Design" from in front of "Disciplines" and "Practices". I do think we may need some ways to reinforce that the nav switcher is representative of a design-oriented ecosystem. Having those labels sort of implied that without having to say anything. Just a thought...

**Comment by mjabbink** [comment]
It’s just that all the above and below the disciplines have it included so just trying to have a visual synchronicity with it all and be crystal clear.

**Comment by mjabbink** [comment]
@sadekbazaraa alternative 

**Foundation**
IBM Brand Center
IBM Design
IBM Design Language
IBM Accessibility

**Design disciplines**
Carbon
Event
Workplace

Practices
Enterprise Design Thinking
IBM Design Research
IBM Design for AI
IBM iX (edited)

**Comment by mjabbink** [comment]
I think I prefer previous and calling things what they are but a discussion to be had. We also have to content with removing Digital and making sure that is clear and evident in Carbon site. From Carbon aim to the dot com library site (essential a PAL for Dotcom).

**Comment by janchild** [comment]
@mjabbink @sadekbazaraa 

I am liking this third one (the last one) because of the simplicity of the mid-section. In one of my versions I had Design in front of each of the headings and I do like the feeling that that gave. It might seem repetitive but it's useful. I like the rhythm of it, and the repetition is a confirmation of where you are. It saves you from spending time thinking about how these options fit together. 

**Design foundations**
IBM Brand Center
IBM Design
IBM Design Language
IBM Accessibility

**Design disciplines**
Carbon
Event
Workplace

**Design practices**
Enterprise Design Thinking
IBM Design Research
IBM Design for AI
IBM iX (edited)

Note that I've also changed **Foundation** to **Foundations**. There are multiple elements there, plus having one heading singular and the other two plural is twanging for me. 

@mjabbink A phased approach with regard to Digital might be better here. Having a plan for the merge, and then making an additional update to the switcher once we've had a chance to message people about it would be helpful for all the people using it.

**Comment by DianaStanciulescu** [comment]
Hi! From my perspective, not knowing the entire strategy and thought that went behind this: 
- repeating design in the labels makes sense, it gives context and I do not mind the repetition
- In the top category, IBM Design sounds like an all encompassing site, and to me it is more of an organizational one... can it be named IBM Design something to make its purpose more clear? Maybe it's just me, but having such a simple big name makes it feel like it sits on top of all the others
- I would put IDL right under BC for the same reason above
- not sure if "carbon" is something everybody understands or if product + digital should be part of the title

**Comment by janchild** [comment]
Hi @DianaStanciulescu, you are right about the order. I see that these are not in the current order and they probably should be, unless there was a reason they were changing? Not sure, @mjabbink if that was intentional.

**Comment by mjabbink** [comment]
It should all get reconsidered. I realize w3.ibm.com communicates IDL and Carbon (IBM Design System) as Practices which makes the switcher already not synched up. Is that even the best way to talk about those sites/content? Are they Practices like IBM Design Research or EDT? They are different indeed. Just pointing out that it all needs to be reconsidered and articulated.

**Comment by mjabbink** [comment]
Another thought

**Foundation**
IBM Brand Center
IBM Design
IBM Design Language
IBM Accessibility

**Design system**
Carbon for Product
Carbon for Dotcom

**Disciplines**
Event Design
Workplace Design

**Practices**
Enterprise Design Thinking
IBM Design Research
IBM Design for AI
IBM iX (edited)

**Comment by DianaStanciulescu** [comment]
Aren't event and workplace also design systems?  I like "design systems" as a category name, it is obvious what they are; "discipline" and "practice" is something I am personally still struggling with

**Comment by mjabbink** [comment]
@DianaStanciulescu technically these are all systems including IDL. But the we speak to it differently in w3 IBM Design site. It all needs some rethinking but we are just trying to do an interim improvement

**Comment by LMapes** [comment]
@mjabbink @janchild @DianaStanciulescu I am new-ish to the team but I can't figure out the distinction between Disciplines and Practices. If those are internal constructs, they may not make sense to the lay user. I liked the iteration of Design foundations, Design systems and Design Practices (OR Design Disciplines) that Jan had suggested because they reinforce that this is a place where design is highly valued.

**Comment by mjabbink** [comment]
@LMapes it was based on how we describe IBM Design In www.ibm.com/design and w3.ibm.com/design. This sites have evolved a bit since we organized the switcher.

**Comment by janchild** [comment]
@jeanservaas As we discussed, could you please mock some of these things up. When @jillianhowarth is back in the office, I'd like for us to run some tests and get some real data to work with. 

FYI @shinytoyrobots

**Comment by DianaStanciulescu** [comment]
Hello! I am not sure if there has been progress on the topic in the meantime, but looking back at the conversation above I repeated here Jan's and Mike's latest suggestions for the switcher, and made 2 other variations on the topic. 

In the TOC part, I think we can replace the first image with the carbon icon and lead people to the carbon page; this change can be implemented now if you all agree. 

For the About IDL page(s) I would surely need more info before starting anything; 

![switcher v1](https://user-images.githubusercontent.com/51086727/95745786-5bd53e80-0c9e-11eb-87d0-19097add7f15.jpg)

**Comment by LMapes** [comment]
@janchild @mjabbink @DianaStanciulescu It seems odd to me to bifurcate Carbon in the nav. If one is for general Carbon and one is for Product, does it make sense to add 'Product' under 'Carbon' in Jan's latest nav that Diana has in the png above? That's short and clean.

**Comment by mjabbink** [comment]
@LMapes Those switcher images are not correct so disregard those.

**Comment by mjabbink** [comment]
Might be more this but still WIP.

<img width="733" alt="Screen Shot 2020-10-12 at 9 30 36 AM" src="https://user-images.githubusercontent.com/32881239/95758125-a5f1fc00-0c6d-11eb-83de-dcb56578937a.png">

**Comment by DianaStanciulescu** [comment]
@mjabbink @LMapes  sorry to have caused confusion, just wanted to revive the conversation. this latest structure makes super sense to me, with the IBM Design site under community and carbon for ibm.com now looking as a subset of the big carbon system.  "Implementation" is also nice since all are systems, so design systems was a bit confusing. 

so apart from the IDL TOC, let me know if there is anything here I can help with.

**Comment by LMapes** [comment]
@mjabbink Liking this version Mike, a lot. I heard someone say the IDL is the WHAT, Carbon is the HOW.
