### ISSUE TITLE
Rebus pattern source files

### ISSUE THREAD

**Issue by kennethhartmann** [carbon-design-system/design-language-website#752]
IBM Logos>Rebus

## Detailed description

@sadekbazaraa I just noticed the Rebus pattern folder and source files are open to the public. As the Rebus requires usage approvals, I think these patterns want to be gated behind an IBM login: https://www.ibm.com/design/language/ibm-logos/rebus#patterns

![Screen Shot 2020-09-01 at 2.08.02 PM.png](https://images.zenhubusercontent.com/5e1e1ddea8ad747aa5d00d85/0e7e684e-60d0-4aac-94ed-0160e262fada)

**Comment by sadekbazaraa** [comment]
@kennethhartmann I wasn't a part of the original conversations and decisions to make this public. I guess the thinking was because these are pre-approved patterns ready to use that they could be made available? 

None of the language says anything about requiring approvals. If that is the case, then we should likely revisit. I'd also question if this is even relevant on this page. Feels like BC material if only a few IBMers and agency partners are allowed to use. Another area where the distinction between IDL and BC is gray and murky. Especially with the consideration of having BC public. 

Of course the simplest solution is to just:
1. move the file to a different Box folder
2. update the link
3. add (w3id required) to the second line of the resource card

**Comment by mjabbink** [comment]
@sadekbazaraa @kennethhartmann What is the story on this issue? Should we close?

**Comment by sadekbazaraa** [comment]
@kennethhartmann I'm seeing 3 options.

1. Leave as is if there's no legal issue with the patterns.
2. Remove Patterns section from IDL page and include on the BC page where we talk about the Rebus.
3. Leave as is on IDL, but just place the asset behind a gate on Box and add "(IBMid required)" to the resource card.

**Comment by mjabbink** [comment]
@sadekbazaraa @kennethhartmann Should this close?

**Comment by sadekbazaraa** [comment]
Great question @mjabbink I think the same issue still stands. Since you have to agree to legal terms in order to use the rebus, I think this section needs to be removed. Actually, it can't really be available on Brand Center either unless you've agreed to all the terms. There's a whole new set of brand assets that are coming and will need thinking through so my suggestion for the time being is to remove this completely. If anyone needs the pattern, they'll find us as they typically do. Would you agree @kennethhartmann ?
