### ISSUE TITLE
remove cookies button and move to footer

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/design-language-website#867]
Remove the cookies button anchored at the bottom of the page and move “Cookie preferences” like https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/ and www.ibm.com

FYI @sadekbazaraa @jeanservaas the cookies button is so bad I can’t take it. I recommend we follow IBM dot com and Carbon for IBM dot com. They also apply it in the footer for Europe. We probably need a spec or a visual for Aux or we add it as the last item in the footer far left column.

The button in mobile is a nuisance to say the least and overlaps with the feedback buttons.

Privacy
Terms of use
IBM.com
Cookie preference

**Comment by sadekbazaraa** [comment]
I hear you @mjabbink such a nuisance! 

I believe @rmathur16 was also looking into this... does the button only appear in the corner briefly or until you've accepted and then it goes away? We were talking about the need to add to the footer like .com because it disappears at some point and needs to always be available. I may be confused about that... either way, I'm completely on board to get rid of the darn thing if we can.

**Comment by mjabbink** [comment]
Hidy hoooo!

**Comment by rmathur16** [comment]
@mjabbink @sadekbazaraa 
I’ve been trying to chase down some of the folks on this but without any luck for now.
This is something similar I and Pavol was discussing on https://github.ibm.com/brand/center/issues/892
When comparing our Brand ecosystem sites with dotcom site. The white cookie preferences button appears just for few seconds on IBM.com pages, in fact on our Brand sites it appears for approx 20 sec and disappears on it’s own even if user does not take any action on it. Yes, we definitely need to inject ‘Cookie preferences’ link on our Brand ecosystem sites footer like the way dotcom is doing. 
Whether we can altogether remove white cookie preferences button remains a question. That’s what I’m trying to figure it out. Thanks.

**Comment by rmathur16** [comment]
On a second thought at present on Brand site when ‘Cookie preferences’ link disappears without user taking any action on it,  I'm wondering whether we are GDPR compliant or not? Since after button disappears user has no place to give consent to collect data. So I think it's mandatory to have ‘Cookie preferences’ link on the footer of our sites.
Thoughts? 
@mjabbink @sadekbazaraa @kennethhartmann

**Comment by mjabbink** [comment]
I think we avoid the issue by placing it in the footer as IBM.com does. I think we’ll escape any Police beatings and incarcerations.

**Comment by Palke** [comment]
@mjabbink @rmathur16 @sadekbazaraa Hi guys. Just to chime in. Bases on articles from the issue https://github.ibm.com/brand/center/issues/892 this text button indeed seems to be requirement.

Carbon for .com and their documentation site (based on the Gatsby Theme) are using solution that was created for them. We could maybe utilize the same, just to avoid having different implementations around.

Implementation flow for them is:
- Create empty "li" element as placeholder with attribute **data-autoid="dds--privacy-cp"**
- DBDM library will (if present) inject the button within this placeholder and hide the white big button from right bottom corner

It does work properly at ibm.com home page as that page is static. On their own documentation site https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/ they did hacky (currently probably only doable) implementation and that does not work properly - on first page this button is injected but navigation to another page will simply re-render the Footer component causing this dynamically injected button to disappear. And it is not comming back.

Since current Gatsby Theme footer allows us to provide only links as "href" + "text" embeding this button properly may require GTC to update footer - and allow us to inject custom element where needed.

As proof of concept I have it done here: https://pages.github.ibm.com/Pavol-Meszaros1/preview/cookie-pref/ 

If we don't opt-in for reusing the same logic (with LI placeholder) I suggest to reach out jleon@us.ibm.com about another options.

**Comment by vpicone** [comment]
This is a consequence of using Tableu, rather than Fathom along with user privacy concerns that I brought up to @rmathur16 and Ken during our meeting. 

Hiding it or tucking it away while storing cookies makes it even more egregious. IBM.com delivers the hidden version based on a users country of origin which is dubious at best. If you go to the French version of the site you'll se the same pop up.

**Comment by Palke** [comment]
@rmathur16 as per my discussion with Vince on Slack we should avoid updating theme component. We can shadow the full Footer as I did here: https://pages.github.ibm.com/Pavol-Meszaros1/preview/cookie-pref/ in order to get it up.

We can now move forward with decision on the technical implementation.

**Comment by mjabbink** [comment]
@rmathur16 @Palke Let’s get what you did for BC applied here please. This was the original issue.
